name: Bootcamp class 1

on:
  push:
    branches: [ master ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
        
    - name: Installing Nodejs
      uses: actions/setup-node@v2-beta
      with: 
        node -version: 12
    
    - name: Install Surge
      run: npm install --global surge
      
    - name: Deploying Surge
      run: surge ./ bootcampfirstclass1.surge.sh/ --token ${{ secrets.BOOTCAMPCLASS }}
      
          
     
