name: Bootcamp class 1

on:
  push:
    branches: [ master ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Installing Nodejs
      uses: actions/setup-node@v2-beta
      with: 
        node -version: 12
    
    - name: Install surge
      run: npm install --global surge
      
    - name: Deploying Surge
      run: surge ./ bootcampfirstclass1.surge.sh/ --token ${{ secrets.BOOTCAMPCLASS }}
      
          
     
